;;;; views.lisp — Pane display functions for Astrolabe

(in-package #:astrolabe)

;;; ─────────────────────────────────────────────────────────────────────
;;; Navigation pane — left side, shows lists of objects
;;; ─────────────────────────────────────────────────────────────────────

(defun display-navigation (frame pane)
  "Display function for the navigation pane."
  (declare (ignore frame))
  (display-breadcrumbs pane)
  (case *current-view*
    (:home       (display-home-nav pane))
    (:project    (display-project-nav pane))
    (:search     (display-search-nav pane))
    (:tag-filter (display-tag-filter-nav pane))
    (:tasks      (display-tasks-nav pane))
    (:agenda         (display-agenda-nav pane))
    (:go-results     (display-go-results-nav pane))
    (:conversations  (display-conversations-nav pane))
    (:conversation   (display-conversation-nav pane))
    (:feeds          (display-feeds-nav pane))
    (:feed-items     (display-feed-items-nav pane))
    (:notifications  (display-notifications-nav pane))
    (:shell          (display-shell-nav pane))
    (:llm            (display-llm-nav pane))
    (:journal        (display-journal-nav pane))
    (:documents      (display-documents-nav pane))
    (:events         (display-events-nav pane))
    (:invoices       (display-invoices-nav pane))
    (:tickets        (display-tickets-nav pane))
    (:repositories   (display-repositories-nav pane))
    (:servers        (display-servers-nav pane))
    (:habits         (display-habits-nav pane))
    (:bookmarks      (display-bookmarks-nav pane))
    (t               (display-home-nav pane))))

(defun display-home-nav (pane)
  "Display the home screen in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  ASTROLABE~%")))
  (terpri pane)

  ;; Active tasks
  (with-drawing-options (pane :ink +yellow+)
    (with-text-face (pane :bold)
      (format pane "  Tasks~%")))
  (let ((tasks (load-open-tasks 15)))
    (if tasks
        (dolist (task tasks)
          (present-task pane task))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no open tasks)~%"))))
  (terpri pane)

  ;; Active projects
  (with-drawing-options (pane :ink +green+)
    (with-text-face (pane :bold)
      (format pane "  Projects~%")))
  (let ((projects (load-active-projects 10)))
    (if projects
        (dolist (project projects)
          (present-project pane project))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no active projects)~%"))))
  (terpri pane)

  ;; Recent notes
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  Recent Notes~%")))
  (let ((notes (load-recent-notes 10)))
    (if notes
        (dolist (note notes)
          (present-note pane note))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no notes yet)~%"))))
  (terpri pane)

  ;; Persons
  (with-drawing-options (pane :ink +magenta+)
    (with-text-face (pane :bold)
      (format pane "  Contacts~%")))
  (let ((persons (load-persons 10)))
    (if persons
        (dolist (person persons)
          (present-person pane person))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no contacts yet)~%"))))
  (terpri pane)

  ;; Recent snippets
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  Snippets~%")))
  (let ((snippets (load-recent-snippets 10)))
    (if snippets
        (dolist (snippet snippets)
          (present-snippet pane snippet))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no snippets yet)~%"))))
  (terpri pane)

  ;; Notifications summary
  (let ((notif-count (unread-notification-count)))
    (when (> notif-count 0)
      (with-drawing-options (pane :ink +yellow+)
        (with-text-face (pane :bold)
          (format pane "  Notifications (~D)~%" notif-count)))
      (let ((recent (load-notifications :limit 3 :unread-only t)))
        (dolist (n recent)
          (present-notification pane n)))
      (terpri pane)))

  ;; Conversations summary
  (let ((convs (load-conversations 5)))
    (when convs
      (with-drawing-options (pane :ink +cyan+)
        (with-text-face (pane :bold)
          (format pane "  Conversations~%")))
      (dolist (conv convs)
        (present-conversation pane conv))
      (terpri pane)))

  ;; Feeds summary
  (let ((feeds (load-feeds 5)))
    (when feeds
      (with-drawing-options (pane :ink +green+)
        (with-text-face (pane :bold)
          (format pane "  Feeds~%")))
      (dolist (feed feeds)
        (present-feed pane feed))
      (terpri pane)))

  ;; Bookmarks
  (let ((bookmarks (load-bookmarks 10)))
    (when bookmarks
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Bookmarks~%")))
      (dolist (bm bookmarks)
        (let ((obj (when (bm-object-type bm)
                    (load-object-by-type-and-id
                     (bm-object-type bm) (bm-object-id bm)))))
          (if obj
              (present-object pane obj)
              (present-bookmark pane bm)))))))

(defun display-project-nav (pane)
  "Display a project's contents in the navigation pane."
  (if (null *current-project*)
      (display-home-nav pane)
      (let ((project *current-project*))
        (with-drawing-options (pane :ink +green+)
          (with-text-face (pane :bold)
            (format pane "  ~A~%" (project-name project))))
        (with-drawing-options (pane :ink +white+)
          (format pane "  ~A~%" (project-description project)))
        (terpri pane)

        ;; Project tasks
        (with-drawing-options (pane :ink +yellow+)
          (with-text-face (pane :bold)
            (format pane "  Tasks~%")))
        (let ((tasks (load-project-tasks (obj-id project))))
          (if tasks
              (dolist (task tasks)
                (present-task pane task))
              (with-drawing-options (pane :ink +white+)
                (format pane "    (no tasks)~%"))))
        (terpri pane)

        ;; Project notes (via links)
        (with-drawing-options (pane :ink +cyan+)
          (with-text-face (pane :bold)
            (format pane "  Notes~%")))
        (let ((linked (load-linked-objects project))
              (notes nil))
          (dolist (link linked)
            (when (string-equal (first link) "note")
              (let ((note (load-note (second link))))
                (when note (push note notes)))))
          (if notes
              (dolist (note (nreverse notes))
                (present-note pane note))
              (with-drawing-options (pane :ink +white+)
                (format pane "    (no notes)~%")))))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Breadcrumbs
;;; ─────────────────────────────────────────────────────────────────────

(defun nav-state-label (state)
  "Return a short label for a navigation state."
  (let ((view (getf state :view))
        (obj  (getf state :object)))
    (cond
      (obj  (obj-display-title obj))
      ((eq view :home) "Home")
      ((eq view :search) (format nil "Search: ~A" (or *search-query* "")))
      ((eq view :agenda) "Agenda")
      ((eq view :tasks) "Tasks")
      ((eq view :tag-filter) (format nil "Tag: ~A" (or *filter-tag* "")))
      (t (string-capitalize (symbol-name view))))))

(defun display-breadcrumbs (pane)
  "Display the navigation breadcrumb trail."
  (when *nav-history*
    (with-drawing-options (pane :ink +white+)
      (format pane "  ")
      (let ((trail (reverse (subseq *nav-history* 0 (min 5 (length *nav-history*))))))
        (dolist (state trail)
          (format pane "~A > " (nav-state-label state))))
      (format pane "*~%"))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Helper — present any object by type
;;; ─────────────────────────────────────────────────────────────────────

(defun present-object (pane obj)
  "Present any astrolabe object as a clickable presentation."
  (cond
    ((typep obj 'note)         (present-note pane obj))
    ((typep obj 'task)         (present-task pane obj))
    ((typep obj 'project)      (present-project pane obj))
    ((typep obj 'person)       (present-person pane obj))
    ((typep obj 'snippet)      (present-snippet pane obj))
    ((typep obj 'conversation) (present-conversation pane obj))
    ((typep obj 'feed)         (present-feed pane obj))
    ((typep obj 'feed-item)    (present-feed-item pane obj))
    ((typep obj 'journal-entry) (present-journal-entry pane obj))
    ((typep obj 'document)      (present-document pane obj))
    ((typep obj 'event)         (present-event pane obj))
    ((typep obj 'invoice)       (present-invoice pane obj))
    ((typep obj 'ticket)        (present-ticket pane obj))
    ((typep obj 'repository)    (present-repository pane obj))
    ((typep obj 'server)        (present-server pane obj))
    ((typep obj 'habit)         (present-habit pane obj))
    ((typep obj 'bookmark)      (present-bookmark pane obj))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Search results view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-search-nav (pane)
  "Display search results in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  Search: ~A~%" (or *search-query* ""))))
  (terpri pane)
  (if *search-results*
      (dolist (obj *search-results*)
        (present-object pane obj))
      (with-drawing-options (pane :ink +white+)
        (format pane "    (no results)~%"))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Tag filter view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-tag-filter-nav (pane)
  "Display objects matching a tag filter."
  (with-drawing-options (pane :ink +yellow+)
    (with-text-face (pane :bold)
      (format pane "  Tag: ~A~%" (or *filter-tag* ""))))
  (terpri pane)
  (if *filter-results*
      (dolist (obj *filter-results*)
        (present-object pane obj))
      (with-drawing-options (pane :ink +white+)
        (format pane "    (no tagged objects)~%"))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Task list view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-tasks-nav (pane)
  "Display filtered task list."
  (with-drawing-options (pane :ink +yellow+)
    (with-text-face (pane :bold)
      (format pane "  Tasks~A~%"
              (case *task-filter*
                (:all   " (all open)")
                (:today " (today)")
                (t      "")))))
  (terpri pane)
  (if *task-filter-results*
      (dolist (task *task-filter-results*)
        (present-task pane task))
      (with-drawing-options (pane :ink +white+)
        (format pane "    (no tasks)~%"))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Agenda view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-agenda-nav (pane)
  "Display the daily agenda view."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  AGENDA~%")))
  (with-drawing-options (pane :ink +white+)
    (format pane "  ~A~%"
            (subseq (local-time:format-timestring nil (local-time:now)
                     :format '((:year 4) #\- (:month 2) #\- (:day 2)))
                    0 10)))
  (terpri pane)

  ;; Overdue
  (when *agenda-overdue*
    (with-drawing-options (pane :ink +red+)
      (with-text-face (pane :bold)
        (format pane "  Overdue~%")))
    (dolist (task *agenda-overdue*)
      (present-task pane task))
    (terpri pane))

  ;; Today
  (with-drawing-options (pane :ink +yellow+)
    (with-text-face (pane :bold)
      (format pane "  Today~%")))
  (if *agenda-today*
      (dolist (task *agenda-today*)
        (present-task pane task))
      (with-drawing-options (pane :ink +white+)
        (format pane "    (nothing due today)~%")))
  (terpri pane)

  ;; Upcoming 7 days
  (with-drawing-options (pane :ink +green+)
    (with-text-face (pane :bold)
      (format pane "  Upcoming (7 days)~%")))
  (if *agenda-upcoming*
      (dolist (task *agenda-upcoming*)
        (present-task pane task))
      (with-drawing-options (pane :ink +white+)
        (format pane "    (nothing upcoming)~%")))
  (terpri pane)

  ;; Recent captures
  (when *agenda-recent*
    (with-drawing-options (pane :ink +cyan+)
      (with-text-face (pane :bold)
        (format pane "  Recent captures (24h)~%")))
    (dolist (obj *agenda-recent*)
      (present-object pane obj))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Go (fuzzy find) results view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-go-results-nav (pane)
  "Display fuzzy-find results."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  Jump to:~%")))
  (terpri pane)
  (if *go-results*
      (dolist (obj *go-results*)
        (present-object pane obj))
      (with-drawing-options (pane :ink +white+)
        (format pane "    (no matches)~%"))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Conversations view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-conversations-nav (pane)
  "Display the conversation list."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  CONVERSATIONS~%")))
  (terpri pane)
  (let ((convs (load-conversations)))
    (if convs
        (dolist (conv convs)
          (present-conversation pane conv))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no conversations yet)~%")))))

(defun display-conversation-nav (pane)
  "Display a message thread in the navigation pane."
  (if (null *current-conversation*)
      (display-conversations-nav pane)
      (progn
        (with-drawing-options (pane :ink +white+)
          (with-text-face (pane :bold)
            (format pane "  ~A~%"
                    (obj-display-title *current-conversation*))))
        (with-drawing-options (pane :ink +white+)
          (format pane "  ~A~%" (conv-jid *current-conversation*)))
        (terpri pane)
        (if *current-messages*
            (dolist (msg *current-messages*)
              (let ((nick (or (xmsg-sender-nick msg) "???"))
                    (body (xmsg-body msg))
                    (ts   (xmsg-created-at msg)))
                (with-drawing-options (pane :ink (if (equal nick "me") +green+ +cyan+))
                  (format pane "  <~A> ~A" nick body))
                (when ts
                  (with-drawing-options (pane :ink +white+)
                    (format pane "  ~A" (subseq ts 11 16))))
                (terpri pane)))
            (with-drawing-options (pane :ink +white+)
              (format pane "    (no messages)~%"))))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Feeds view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-feeds-nav (pane)
  "Display the feed subscription list."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  FEEDS~%")))
  (terpri pane)
  (let ((feeds (load-feeds)))
    (if feeds
        (dolist (feed feeds)
          (present-feed pane feed))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no subscriptions yet)~%")
          (format pane "    Use: Subscribe [url]~%")))))

(defun display-feed-items-nav (pane)
  "Display articles for the current feed."
  (if (null *current-feed*)
      (display-feeds-nav pane)
      (progn
        (with-drawing-options (pane :ink +white+)
          (with-text-face (pane :bold)
            (format pane "  ~A~%" (obj-display-title *current-feed*))))
        (when (feed-description *current-feed*)
          (with-drawing-options (pane :ink +white+)
            (format pane "  ~A~%" (feed-description *current-feed*))))
        (terpri pane)
        (if *current-feed-items*
            (dolist (fi *current-feed-items*)
              (present-feed-item pane fi))
            (with-drawing-options (pane :ink +white+)
              (format pane "    (no articles)~%"))))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Notifications view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-notifications-nav (pane)
  "Display notifications in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  NOTIFICATIONS~%")))
  (let ((count (unread-notification-count)))
    (when (> count 0)
      (with-drawing-options (pane :ink +yellow+)
        (format pane "  ~D unread~%" count))))
  (terpri pane)
  (let ((notifs (load-notifications :limit 30)))
    (if notifs
        (dolist (notif notifs)
          (present-notification pane notif))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no notifications)~%")))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Shell output view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-shell-nav (pane)
  "Display shell command output in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  SHELL~%")))
  (when *shell-command*
    (with-drawing-options (pane :ink +cyan+)
      (format pane "  $ ~A~%" *shell-command*))
    (with-drawing-options (pane :ink (if (and *shell-exit-code* (= *shell-exit-code* 0))
                                        +green+ +red+))
      (format pane "  Exit: ~A~%" (or *shell-exit-code* "?"))))
  (terpri pane)
  (when *shell-output*
    (with-drawing-options (pane :ink +white+)
      ;; Truncate very long output for the nav pane
      (let ((lines (cl-ppcre:split "\\n" *shell-output*))
            (max-lines 40))
        (loop for line in lines
              for i from 0 below max-lines
              do (format pane "  ~A~%" line))
        (when (> (length lines) max-lines)
          (with-drawing-options (pane :ink +yellow+)
            (format pane "  ... (~D more lines)~%" (- (length lines) max-lines))))))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Phase 6: Extended object views
;;; ─────────────────────────────────────────────────────────────────────

(defun display-journal-nav (pane)
  "Display journal entries in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  JOURNAL~%")))
  (terpri pane)
  (let ((entries (load-journal-entries 30)))
    (if entries
        (dolist (je entries)
          (present-journal-entry pane je))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no journal entries)~%")
          (format pane "    Use: Journal~%")))))

(defun display-documents-nav (pane)
  "Display documents in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  DOCUMENTS~%")))
  (terpri pane)
  (let ((docs (load-documents)))
    (if docs
        (dolist (doc docs)
          (present-document pane doc))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no documents)~%")
          (format pane "    Use: Add Document [title]~%")))))

(defun display-events-nav (pane)
  "Display events in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  EVENTS~%")))
  ;; Upcoming
  (let ((upcoming (load-upcoming-events 14)))
    (when upcoming
      (terpri pane)
      (with-drawing-options (pane :ink +white+)
        (format pane "  Upcoming:~%"))
      (dolist (evt upcoming)
        (present-event pane evt))))
  ;; All
  (terpri pane)
  (let ((all (load-events 20)))
    (if all
        (progn
          (with-drawing-options (pane :ink +white+)
            (format pane "  All Events:~%"))
          (dolist (evt all)
            (present-event pane evt)))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no events)~%")
          (format pane "    Use: Add Event [title]~%")))))

(defun display-invoices-nav (pane)
  "Display invoices in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  INVOICES~%")))
  ;; Open invoices first
  (let ((open (load-open-invoices)))
    (when open
      (terpri pane)
      (with-drawing-options (pane :ink +white+)
        (format pane "  Open:~%"))
      (dolist (inv open)
        (present-invoice pane inv))))
  ;; All
  (terpri pane)
  (let ((all (load-invoices 20)))
    (if all
        (progn
          (with-drawing-options (pane :ink +white+)
            (format pane "  All:~%"))
          (dolist (inv all)
            (present-invoice pane inv)))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no invoices)~%")
          (format pane "    Use: Add Invoice [title]~%")))))

(defun display-tickets-nav (pane)
  "Display tickets in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  TICKETS~%")))
  (terpri pane)
  (let ((open (load-open-tickets)))
    (if open
        (dolist (tkt open)
          (present-ticket pane tkt))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no open tickets)~%")
          (format pane "    Use: File Ticket [title]~%")))))

(defun display-repositories-nav (pane)
  "Display repositories in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  REPOSITORIES~%")))
  (terpri pane)
  (let ((repos (load-repositories)))
    (if repos
        (dolist (repo repos)
          (present-repository pane repo))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no repositories)~%")
          (format pane "    Use: Add Repository [name]~%")))))

(defun display-servers-nav (pane)
  "Display servers in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  SERVERS~%")))
  (terpri pane)
  (let ((servers (load-servers)))
    (if servers
        (dolist (srv servers)
          (present-server pane srv))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no servers)~%")
          (format pane "    Use: Add Server [name]~%")))))

(defun display-habits-nav (pane)
  "Display habits in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  HABITS~%")))
  (terpri pane)
  (let ((habits (load-habits)))
    (if habits
        (dolist (hab habits)
          (present-habit pane hab))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no habits)~%")
          (format pane "    Use: Add Habit [name]~%")))))

(defun display-bookmarks-nav (pane)
  "Display bookmarks in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  BOOKMARKS~%")))
  (terpri pane)
  (let ((bookmarks (load-bookmarks)))
    (if bookmarks
        (dolist (bm bookmarks)
          (present-bookmark pane bm))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no bookmarks)~%")
          (format pane "    Use: Bookmark [url] [title]~%")))))

;;; ─────────────────────────────────────────────────────────────────────
;;; LLM response view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-llm-nav (pane)
  "Display LLM response in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  AI ASSISTANT~%")))
  (when *llm-model-used*
    (with-drawing-options (pane :ink +cyan+)
      (format pane "  Model: ~A~%" *llm-model-used*)))
  (terpri pane)
  (when *llm-response*
    (with-drawing-options (pane :ink +white+)
      (let ((lines (cl-ppcre:split "\\n" *llm-response*))
            (max-lines 50))
        (loop for line in lines
              for i from 0 below max-lines
              do (format pane "  ~A~%" line))
        (when (> (length lines) max-lines)
          (with-drawing-options (pane :ink +yellow+)
            (format pane "  ... (~D more lines, see detail pane)~%"
                    (- (length lines) max-lines))))))))

(defun display-llm-detail (pane)
  "Display full LLM response in the detail pane."
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  AI Response~%")))
  (when *llm-model-used*
    (with-drawing-options (pane :ink +cyan+)
      (format pane "  Model: ~A~%" *llm-model-used*)))
  (terpri pane)
  (when *llm-prompt*
    (with-drawing-options (pane :ink +yellow+)
      (format pane "  Prompt: ~A~%"
              (if (> (length *llm-prompt*) 120)
                  (concatenate 'string (subseq *llm-prompt* 0 120) "...")
                  *llm-prompt*)))
    (terpri pane))
  (when *llm-response*
    (with-drawing-options (pane :ink +white+)
      (let ((lines (cl-ppcre:split "\\n" *llm-response*)))
        (dolist (line lines)
          (format pane "  ~A~%" line))))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Status bar
;;; ─────────────────────────────────────────────────────────────────────

(defun display-status-bar (frame pane)
  "Display the persistent status bar."
  (declare (ignore frame))
  (with-drawing-options (pane :ink +white+)
    (let* ((view-label (case *current-view*
                         (:home "Home")
                         (:project (if *current-project*
                                       (project-name *current-project*)
                                       "Project"))
                         (:search (format nil "Search: ~A" (or *search-query* "")))
                         (:tag-filter (format nil "Tag: ~A" (or *filter-tag* "")))
                         (:tasks "Tasks")
                         (:agenda "Agenda")
                         (:go-results "Jump")
                         (:conversations "Conversations")
                         (:conversation (if *current-conversation*
                                            (obj-display-title *current-conversation*)
                                            "Chat"))
                         (:feeds "Feeds")
                         (:feed-items (if *current-feed*
                                          (obj-display-title *current-feed*)
                                          "Articles"))
                         (:notifications "Notifications")
                         (:shell (format nil "$ ~A" (or *shell-command* "shell")))
                         (:llm (format nil "AI (~A)" (or *llm-model-used* *ollama-model*)))
                         (:journal "Journal")
                         (:documents "Documents")
                         (:events "Events")
                         (:invoices "Invoices")
                         (:tickets "Tickets")
                         (:repositories "Repositories")
                         (:servers "Servers")
                         (:habits "Habits")
                         (:bookmarks "Bookmarks")
                         (t "Home")))
           (task-count (length (db-query "SELECT id FROM tasks
                                          WHERE deleted_at IS NULL
                                            AND status IN ('todo','active','waiting')")))
           (notif-count (unread-notification-count))
           (now (subseq (local-time:format-timestring nil (local-time:now)
                          :format '((:hour 2) #\: (:min 2)))
                        0 5)))
      (let ((batch-count (length *batch-selection*)))
        (format pane " ~A  |  ~D open tasks~A~A  |  ~A"
                view-label task-count
                (if (> notif-count 0) (format nil "  |  ~D notif" notif-count) "")
                (if (> batch-count 0) (format nil "  |  ~D selected" batch-count) "")
                now)))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Detail pane — right side, shows selected object
;;; ─────────────────────────────────────────────────────────────────────

(defun display-detail (frame pane)
  "Display function for the detail pane."
  (declare (ignore frame))
  (cond
    (*current-object*
     (display-object-detail pane *current-object*))
    ((and (eq *current-view* :shell) *shell-output*)
     (display-shell-detail pane))
    ((and (eq *current-view* :llm) *llm-response*)
     (display-llm-detail pane))
    (t (display-welcome pane))))

(defun display-shell-detail (pane)
  "Display full shell output in the detail pane."
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  $ ~A~%" (or *shell-command* ""))))
  (with-drawing-options (pane :ink (if (and *shell-exit-code* (= *shell-exit-code* 0))
                                      +green+ +red+))
    (format pane "  Exit: ~A~%" (or *shell-exit-code* "?")))
  (terpri pane)
  (with-drawing-options (pane :ink +white+)
    (let ((lines (cl-ppcre:split "\\n" *shell-output*)))
      (dolist (line lines)
        (format pane "  ~A~%" line)))))

(defun display-welcome (pane)
  "Display a welcome message when nothing is selected."
  (terpri pane)
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  Welcome to Astrolabe~%")))
  (terpri pane)
  (with-drawing-options (pane :ink +white+)
    (format pane "  Navigate notes, tasks, systems, and signals.~%")
    (terpri pane)
    (format pane "  Create:~%")
    (format pane "    Capture Note [title]     — create a note~%")
    (format pane "    Add Task [title]         — create a task~%")
    (format pane "    New Project [name]       — create a project~%")
    (format pane "    Add Person [name]        — add a contact~%")
    (format pane "    Capture Snippet [text]   — save a snippet~%")
    (terpri pane)
    (format pane "  Actions:~%")
    (format pane "    Complete Task [task]     — mark task done~%")
    (format pane "    Link [source] [target]  — link two objects~%")
    (format pane "    Shell [command]          — run a shell command~%")
    (format pane "    Export [object]          — export as markdown~%")
    (format pane "    Export Project Report    — generate status report~%")
    (terpri pane)
    (format pane "  Templates:~%")
    (format pane "    List Templates           — show available templates~%")
    (format pane "    Capture Note Template    — note from template~%")
    (format pane "    Add Task Template        — task from template~%")
    (terpri pane)
    (format pane "  Batch:~%")
    (format pane "    Select [object]          — add to batch~%")
    (format pane "    Batch Tag [tag]          — tag all selected~%")
    (format pane "    Batch Complete           — complete selected tasks~%")
    (format pane "    Batch Delete             — delete all selected~%")
    (terpri pane)
    (format pane "  Navigate:~%")
    (format pane "    Home                     — return to home~%")
    (format pane "    Check Reminders          — check overdue tasks~%")
    (format pane "    Reload Commands          — reload user commands~%")
    (format pane "    Quit                     — exit Astrolabe~%")
    (terpri pane)
    (format pane "  Quick keys:~%")
    (format pane "    C-n  Capture Note    C-b  Back~%")
    (format pane "    C-t  Add Task        C-f  Forward~%")
    (format pane "    C-s  Search          C-a  Agenda~%")
    (format pane "    C-h  Home            C-g  Go (fuzzy find)~%")
    (terpri pane)
    (format pane "  Click any item to see its details.~%")
    (format pane "  Tab cycles focus between panes.~%")))

(defgeneric display-object-detail (pane object)
  (:documentation "Display the detail view for an object."))

(defun display-tags (pane object)
  "Display tags for an object, if any."
  (let ((tags (load-tags-for-object object)))
    (when tags
      (with-drawing-options (pane :ink +yellow+)
        (format pane "  Tags: ~{~A~^, ~}~%" (mapcar #'second tags))))))

(defmethod display-object-detail (pane (note note))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (note-title note))))
  (when (obj-created-at note)
    (with-drawing-options (pane :ink +white+)
      (format pane "  Created: ~A~%" (obj-created-at note))))
  (when (obj-updated-at note)
    (with-drawing-options (pane :ink +white+)
      (format pane "  Updated: ~A~%" (obj-updated-at note))))
  (terpri pane)
  (display-tags pane note)
  (terpri pane)
  (let ((body (note-body note)))
    (when (and body (> (length body) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" body))))
  (display-links pane note))

(defmethod display-object-detail (pane (person person))
  (terpri pane)
  (with-drawing-options (pane :ink +magenta+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (person-name person))))
  (with-drawing-options (pane :ink +white+)
    (when (person-first-name person)
      (format pane "  Name:     ~A~A~%"
              (person-first-name person)
              (if (person-last-name person)
                  (format nil " ~A" (person-last-name person)) "")))
    (when (person-nickname person)
      (format pane "  Nickname: ~A~%" (person-nickname person)))
    (when (person-email person)
      (format pane "  Email:    ~A~%" (person-email person)))
    (when (person-email2 person)
      (format pane "  Email 2:  ~A~%" (person-email2 person)))
    (when (person-phone person)
      (format pane "  Phone:    ~A~%" (person-phone person)))
    (when (person-phone2 person)
      (format pane "  Phone 2:  ~A~%" (person-phone2 person)))
    (when (person-organization person)
      (format pane "  Org:      ~A~%" (person-organization person)))
    (when (person-job-title person)
      (format pane "  Title:    ~A~%" (person-job-title person)))
    (when (person-role person)
      (format pane "  Role:     ~A~%" (person-role person)))
    (when (person-website person)
      (format pane "  Website:  ~A~%" (person-website person)))
    (when (person-address person)
      (format pane "  Address:  ~A~%" (person-address person))
      (when (person-city person)
        (format pane "            ~A~A ~A~%"
                (person-city person)
                (if (person-state person)
                    (format nil ", ~A" (person-state person)) "")
                (or (person-postal-code person) "")))
      (when (person-country person)
        (format pane "            ~A~%" (person-country person))))
    (when (person-birthday person)
      (format pane "  Birthday: ~A~%" (person-birthday person)))
    (when (person-xmpp-jid person)
      (format pane "  XMPP:     ~A~%" (person-xmpp-jid person)))
    (when (person-matrix-id person)
      (format pane "  Matrix:   ~A~%" (person-matrix-id person)))
    (when (person-irc-nick person)
      (format pane "  IRC:      ~A~%" (person-irc-nick person)))
    (when (person-last-contacted person)
      (format pane "  Last contact: ~A~%" (person-last-contacted person)))
    (when (person-contact-frequency person)
      (format pane "  Frequency:    ~A~%" (person-contact-frequency person)))
    (when (obj-created-at person)
      (format pane "  Created:  ~A~%" (obj-created-at person))))
  (terpri pane)
  (let ((notes (person-notes person)))
    (when (and notes (> (length notes) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" notes))
      (terpri pane)))
  (display-tags pane person)
  (display-links pane person))

(defmethod display-object-detail (pane (snippet snippet))
  (terpri pane)
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (obj-display-title snippet))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Type: ~A~%" (snippet-content-type snippet))
    (when (snippet-language snippet)
      (format pane "  Language: ~A~%" (snippet-language snippet)))
    (when (snippet-source snippet)
      (format pane "  Source: ~A~%" (snippet-source snippet)))
    (when (obj-created-at snippet)
      (format pane "  Created: ~A~%" (obj-created-at snippet))))
  (terpri pane)
  (with-drawing-options (pane :ink +white+)
    (format pane "  ~A~%" (snippet-content snippet)))
  (terpri pane)
  (display-tags pane snippet)
  (display-links pane snippet))

(defmethod display-object-detail (pane (task task))
  (terpri pane)
  (with-drawing-options (pane :ink (task-priority-ink (task-priority task)))
    (with-text-face (pane :bold)
      (format pane "  ~A ~A~%" (task-status-marker (task-status task)) (task-title task))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Status:   ~A~%" (task-status task))
    (format pane "  Priority: ~A~%" (task-priority task))
    (when (task-due-date task)
      (format pane "  Due:      ~A~%" (task-due-date task)))
    (when (task-scheduled-date task)
      (format pane "  Scheduled: ~A~%" (task-scheduled-date task)))
    (when (task-completed-at task)
      (format pane "  Completed: ~A~%" (task-completed-at task)))
    (when (task-context task)
      (format pane "  Context:  ~A~%" (task-context task)))
    (when (task-effort-minutes task)
      (format pane "  Effort:   ~Dmin~A~%" (task-effort-minutes task)
              (if (task-actual-minutes task)
                  (format nil " (actual: ~Dmin)" (task-actual-minutes task))
                  "")))
    (when (task-recurrence task)
      (format pane "  Recurs:   ~A~%" (task-recurrence task)))
    (when (obj-created-at task)
      (format pane "  Created:  ~A~%" (obj-created-at task))))
  (display-tags pane task)
  (terpri pane)
  (let ((desc (task-description task)))
    (when (and desc (> (length desc) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" desc))
      (terpri pane)))
  (let ((notes (task-notes task)))
    (when (and notes (> (length notes) 0))
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Notes:~%"))
        (format pane "  ~A~%" notes))
      (terpri pane)))
  ;; Subtasks
  (when (obj-id task)
    (let ((subtasks (load-subtasks (obj-id task))))
      (when subtasks
        (with-drawing-options (pane :ink +yellow+)
          (with-text-face (pane :bold)
            (format pane "  Subtasks:~%")))
        (dolist (st subtasks)
          (present-task pane st))
        (terpri pane))))
  (display-links pane task))

(defmethod display-object-detail (pane (project project))
  (terpri pane)
  (with-drawing-options (pane :ink +green+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (project-name project))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Status:   ~A~%" (project-status project))
    (format pane "  Priority: ~A~%" (project-priority project))
    (when (project-area project)
      (format pane "  Area:     ~A~%" (project-area project)))
    (when (project-start-date project)
      (format pane "  Started:  ~A~%" (project-start-date project)))
    (when (project-target-date project)
      (format pane "  Target:   ~A~%" (project-target-date project)))
    (when (project-completed-at project)
      (format pane "  Completed: ~A~%" (project-completed-at project)))
    (when (obj-created-at project)
      (format pane "  Created:  ~A~%" (obj-created-at project))))
  (display-tags pane project)
  (terpri pane)
  (let ((desc (project-description project)))
    (when (and desc (> (length desc) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" desc))
      (terpri pane)))
  (let ((pnotes (project-notes project)))
    (when (and pnotes (> (length pnotes) 0))
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Notes:~%"))
        (format pane "  ~A~%" pnotes))
      (terpri pane)))
  ;; Task progress
  (let ((tasks (load-project-tasks (obj-id project))))
    (let ((total (length tasks))
          (done (count-if (lambda (tk) (string-equal (task-status tk) "done")) tasks)))
      (with-drawing-options (pane :ink +yellow+)
        (with-text-face (pane :bold)
          (format pane "  Tasks: ~D/~D complete~%" done total))))
    ;; Show open tasks inline
    (let ((open (remove-if (lambda (tk) (string-equal (task-status tk) "done")) tasks)))
      (dolist (task open)
        (present-task pane task))))
  (terpri pane)
  ;; Linked persons
  (let* ((linked (load-linked-objects project))
         (persons nil))
    (dolist (link linked)
      (when (string-equal (first link) "person")
        (let ((p (load-person (second link))))
          (when p (push p persons)))))
    (when persons
      (with-drawing-options (pane :ink +magenta+)
        (with-text-face (pane :bold)
          (format pane "  People:~%")))
      (dolist (p (nreverse persons))
        (present-person pane p))
      (terpri pane)))
  (display-links pane project))

(defmethod display-object-detail (pane (conv conversation))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (obj-display-title conv))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  JID:     ~A~%" (conv-jid conv))
    (format pane "  Type:    ~A~%" (conv-type conv))
    (when (conv-last-activity conv)
      (format pane "  Last:    ~A~%" (conv-last-activity conv)))
    (format pane "  Unread:  ~D~%" (conv-unread-count conv)))
  (terpri pane)
  ;; Show recent messages in detail pane
  (let ((msgs (load-messages (conv-id conv) 20)))
    (when msgs
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Recent messages:~%")))
      (terpri pane)
      (dolist (msg (nreverse msgs))
        (let ((nick (or (xmsg-sender-nick msg) "???"))
              (body (xmsg-body msg))
              (ts   (xmsg-created-at msg)))
          (with-drawing-options (pane :ink (if (equal nick "me") +green+ +cyan+))
            (format pane "  <~A> ~A" nick body))
          (when ts
            (with-drawing-options (pane :ink +white+)
              (format pane "  ~A" (subseq ts 11 16))))
          (terpri pane))))))

(defmethod display-object-detail (pane (fi feed-item))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (obj-display-title fi))))
  (with-drawing-options (pane :ink +white+)
    (when (fi-author fi)
      (format pane "  Author:    ~A~%" (fi-author fi)))
    (when (fi-published-at fi)
      (format pane "  Published: ~A~%" (fi-published-at fi)))
    (when (fi-url fi)
      (format pane "  URL:       ~A~%" (fi-url fi)))
    (format pane "  Read:      ~A~%" (if (= (fi-read fi) 1) "yes" "no"))
    (when (= (fi-starred fi) 1)
      (format pane "  Starred:   yes~%")))
  (terpri pane)
  (let ((content (or (fi-content fi) (fi-summary fi) "")))
    (when (> (length content) 0)
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" content)))))

(defmethod display-object-detail (pane (f feed))
  (terpri pane)
  (with-drawing-options (pane :ink +green+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (obj-display-title f))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  URL:       ~A~%" (feed-url f))
    (when (feed-site-url f)
      (format pane "  Site:      ~A~%" (feed-site-url f)))
    (format pane "  Type:      ~A~%" (feed-feed-type f))
    (format pane "  Unread:    ~D~%" (feed-unread-count f))
    (when (feed-last-fetched f)
      (format pane "  Fetched:   ~A~%" (feed-last-fetched f)))
    (when (and (feed-last-error f) (> (length (feed-last-error f)) 0))
      (with-drawing-options (pane :ink +red+)
        (format pane "  Error:     ~A~%" (feed-last-error f))))
    (when (feed-description f)
      (terpri pane)
      (format pane "  ~A~%" (feed-description f)))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Phase 6: Extended object detail views
;;; ─────────────────────────────────────────────────────────────────────

(defmethod display-object-detail (pane (je journal-entry))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  Journal: ~A~%" (or (je-entry-date je) ""))))
  (when (and (je-title je) (> (length (je-title je)) 0))
    (with-drawing-options (pane :ink +white+)
      (format pane "  Title: ~A~%" (je-title je))))
  (when (je-mood je)
    (with-drawing-options (pane :ink +yellow+)
      (format pane "  Mood: ~A~%" (je-mood je))))
  (when (and (je-tags je) (> (length (je-tags je)) 0))
    (with-drawing-options (pane :ink +yellow+)
      (format pane "  Tags: ~A~%" (je-tags je))))
  (terpri pane)
  (let ((body (je-body je)))
    (when (and body (> (length body) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" body))))
  (display-tags pane je)
  (display-links pane je))

(defmethod display-object-detail (pane (doc document))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (doc-title doc))))
  (with-drawing-options (pane :ink +white+)
    (when (doc-file-path doc)
      (format pane "  Path: ~A~%" (doc-file-path doc)))
    (when (doc-file-type doc)
      (format pane "  Type: ~A~%" (doc-file-type doc)))
    (when (doc-file-size doc)
      (format pane "  Size: ~A bytes~%" (doc-file-size doc)))
    (when (doc-version doc)
      (format pane "  Version: ~A~%" (doc-version doc)))
    (when (obj-created-at doc)
      (format pane "  Created: ~A~%" (obj-created-at doc))))
  (terpri pane)
  (let ((desc (doc-description doc)))
    (when (and desc (> (length desc) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" desc))
      (terpri pane)))
  (let ((notes (doc-notes doc)))
    (when (and notes (> (length notes) 0))
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Notes:~%"))
        (format pane "  ~A~%" notes))))
  (display-tags pane doc)
  (display-links pane doc))

(defmethod display-object-detail (pane (evt event))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (event-title evt))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Status:   ~A~%" (event-status evt))
    (when (event-start-time evt)
      (format pane "  Start:    ~A~%" (event-start-time evt)))
    (when (event-end-time evt)
      (format pane "  End:      ~A~%" (event-end-time evt)))
    (when (= (event-all-day evt) 1)
      (format pane "  All day:  yes~%"))
    (when (event-location evt)
      (format pane "  Location: ~A~%" (event-location evt)))
    (when (event-recurrence evt)
      (format pane "  Recurs:   ~A~%" (event-recurrence evt)))
    (when (event-reminder-minutes evt)
      (format pane "  Reminder: ~D min before~%" (event-reminder-minutes evt)))
    (when (obj-created-at evt)
      (format pane "  Created:  ~A~%" (obj-created-at evt))))
  (terpri pane)
  (let ((desc (event-description evt)))
    (when (and desc (> (length desc) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" desc))
      (terpri pane)))
  (let ((notes (event-notes evt)))
    (when (and notes (> (length notes) 0))
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Notes:~%"))
        (format pane "  ~A~%" notes))))
  (display-tags pane evt)
  (display-links pane evt))

(defmethod display-object-detail (pane (inv invoice))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (obj-display-title inv))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Type:         ~A~%" (inv-type inv))
    (format pane "  Status:       ~A~%" (inv-status inv))
    (when (inv-amount inv)
      (format pane "  Amount:       ~A ~A~%" (inv-currency inv) (inv-amount inv)))
    (when (inv-counterparty inv)
      (format pane "  Counterparty: ~A~%" (inv-counterparty inv)))
    (when (inv-reference inv)
      (format pane "  Reference:    ~A~%" (inv-reference inv)))
    (when (inv-issued-date inv)
      (format pane "  Issued:       ~A~%" (inv-issued-date inv)))
    (when (inv-due-date inv)
      (format pane "  Due:          ~A~%" (inv-due-date inv)))
    (when (inv-paid-date inv)
      (format pane "  Paid:         ~A~%" (inv-paid-date inv)))
    (when (inv-file-path inv)
      (format pane "  File:         ~A~%" (inv-file-path inv)))
    (when (obj-created-at inv)
      (format pane "  Created:      ~A~%" (obj-created-at inv))))
  (terpri pane)
  (let ((notes (inv-notes inv)))
    (when (and notes (> (length notes) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" notes))))
  (display-tags pane inv)
  (display-links pane inv))

(defmethod display-object-detail (pane (tkt ticket))
  (terpri pane)
  (with-drawing-options (pane :ink (task-priority-ink (ticket-priority tkt)))
    (with-text-face (pane :bold)
      (format pane "  [~A] ~A~%" (ticket-status-marker (ticket-status tkt)) (ticket-title tkt))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Status:   ~A~%" (ticket-status tkt))
    (format pane "  Priority: ~A~%" (ticket-priority tkt))
    (when (ticket-severity tkt)
      (format pane "  Severity: ~A~%" (ticket-severity tkt)))
    (when (ticket-assigned-to tkt)
      (let ((p (load-person (ticket-assigned-to tkt))))
        (when p (format pane "  Assigned: ~A~%" (person-name p)))))
    (when (ticket-project-id tkt)
      (let ((prj (load-project (ticket-project-id tkt))))
        (when prj (format pane "  Project:  ~A~%" (project-name prj)))))
    (when (and (ticket-labels tkt) (> (length (ticket-labels tkt)) 0))
      (format pane "  Labels:   ~A~%" (ticket-labels tkt)))
    (when (ticket-resolved-at tkt)
      (format pane "  Resolved: ~A~%" (ticket-resolved-at tkt)))
    (when (obj-created-at tkt)
      (format pane "  Created:  ~A~%" (obj-created-at tkt))))
  (terpri pane)
  (let ((desc (ticket-description tkt)))
    (when (and desc (> (length desc) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" desc))
      (terpri pane)))
  (when (ticket-resolution tkt)
    (with-drawing-options (pane :ink +green+)
      (with-text-face (pane :bold)
        (format pane "  Resolution:~%"))
      (format pane "  ~A~%" (ticket-resolution tkt)))
    (terpri pane))
  (let ((notes (ticket-notes tkt)))
    (when (and notes (> (length notes) 0))
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Notes:~%"))
        (format pane "  ~A~%" notes))))
  (display-tags pane tkt)
  (display-links pane tkt))

(defmethod display-object-detail (pane (repo repository))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (repo-name repo))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Branch: ~A~%" (or (repo-branch repo) "main"))
    (when (repo-path repo)
      (format pane "  Path:   ~A~%" (repo-path repo)))
    (when (repo-remote-url repo)
      (format pane "  Remote: ~A~%" (repo-remote-url repo)))
    (when (repo-project-id repo)
      (let ((prj (load-project (repo-project-id repo))))
        (when prj (format pane "  Project: ~A~%" (project-name prj)))))
    (when (repo-last-checked repo)
      (format pane "  Checked: ~A~%" (repo-last-checked repo)))
    (when (obj-created-at repo)
      (format pane "  Created: ~A~%" (obj-created-at repo))))
  (terpri pane)
  (let ((desc (repo-description repo)))
    (when (and desc (> (length desc) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" desc))
      (terpri pane)))
  ;; Recent commits
  (let ((commits (repo-recent-commits repo 10)))
    (when commits
      (with-drawing-options (pane :ink +yellow+)
        (with-text-face (pane :bold)
          (format pane "  Recent commits:~%")))
      (with-drawing-options (pane :ink +white+)
        (dolist (c commits)
          (format pane "    ~A~%" c)))
      (terpri pane)))
  (display-tags pane repo)
  (display-links pane repo))

(defmethod display-object-detail (pane (srv server))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (server-name srv))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Hostname: ~A~%" (server-hostname srv))
    (format pane "  Port:     ~D~%" (server-port srv))
    (when (server-username srv)
      (format pane "  User:     ~A~%" (server-username srv)))
    (when (server-ssh-key srv)
      (format pane "  SSH Key:  ~A~%" (server-ssh-key srv)))
    (when (server-os srv)
      (format pane "  OS:       ~A~%" (server-os srv))))
  (with-drawing-options (pane :ink (cond ((string-equal (server-status srv) "online") +green+)
                                        ((string-equal (server-status srv) "offline") +red+)
                                        (t +white+)))
    (format pane "  Status:   ~A~%" (server-status srv)))
  (with-drawing-options (pane :ink +white+)
    (when (server-last-checked srv)
      (format pane "  Checked:  ~A~%" (server-last-checked srv)))
    (when (server-project-id srv)
      (let ((prj (load-project (server-project-id srv))))
        (when prj (format pane "  Project:  ~A~%" (project-name prj)))))
    (when (obj-created-at srv)
      (format pane "  Created:  ~A~%" (obj-created-at srv))))
  (terpri pane)
  (let ((desc (server-description srv)))
    (when (and desc (> (length desc) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" desc))
      (terpri pane)))
  (let ((notes (server-notes srv)))
    (when (and notes (> (length notes) 0))
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Notes:~%"))
        (format pane "  ~A~%" notes))))
  (display-tags pane srv)
  (display-links pane srv))

(defmethod display-object-detail (pane (hab habit))
  (terpri pane)
  (with-drawing-options (pane :ink (if (> (habit-streak hab) 0) +green+ +cyan+))
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (habit-name hab))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Frequency:  ~A~%" (habit-frequency hab))
    (format pane "  Target:     ~D per period~%" (habit-target-count hab))
    (format pane "  Active:     ~A~%" (if (= (habit-active hab) 1) "yes" "paused")))
  (terpri pane)
  (with-drawing-options (pane :ink +green+)
    (format pane "  Streak:     ~D~%" (habit-streak hab))
    (format pane "  Best:       ~D~%" (habit-best-streak hab)))
  (with-drawing-options (pane :ink +white+)
    (when (habit-last-logged hab)
      (format pane "  Last logged: ~A~%" (habit-last-logged hab)))
    (when (obj-created-at hab)
      (format pane "  Created:    ~A~%" (obj-created-at hab))))
  (terpri pane)
  (let ((desc (habit-description hab)))
    (when (and desc (> (length desc) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" desc))))
  (display-tags pane hab)
  (display-links pane hab))

(defmethod display-object-detail (pane (bm bookmark))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (bm-title bm))))
  (with-drawing-options (pane :ink +white+)
    (when (bm-url bm)
      (format pane "  URL:         ~A~%" (bm-url bm)))
    (when (bm-description bm)
      (format pane "  Description: ~A~%" (bm-description bm)))
    (when (bm-object-type bm)
      (format pane "  Linked:      ~A #~A~%" (bm-object-type bm) (bm-object-id bm)))
    (when (obj-created-at bm)
      (format pane "  Created:     ~A~%" (obj-created-at bm))))
  (display-tags pane bm)
  (display-links pane bm))

(defun display-links (pane object)
  "Display linked objects for OBJECT."
  (let ((linked (load-linked-objects object)))
    (when linked
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Linked:~%")))
      (dolist (link linked)
        (let* ((type-name (first link))
               (id (second link))
               (relation (third link))
               (obj (load-object-by-type-and-id type-name id)))
          (when obj
            (with-drawing-options (pane :ink +white+)
              (format pane "    ~A " (or relation "—")))
            (present-object pane obj)))))))
