;;;; views.lisp — Pane display functions for Astrolabe

(in-package #:astrolabe)

;;; ─────────────────────────────────────────────────────────────────────
;;; Navigation pane — left side, shows lists of objects
;;; ─────────────────────────────────────────────────────────────────────

(defun display-navigation (frame pane)
  "Display function for the navigation pane."
  (declare (ignore frame))
  (case *current-view*
    (:home       (display-home-nav pane))
    (:project    (display-project-nav pane))
    (:search     (display-search-nav pane))
    (:tag-filter (display-tag-filter-nav pane))
    (:tasks      (display-tasks-nav pane))
    (t           (display-home-nav pane))))

(defun display-home-nav (pane)
  "Display the home screen in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  ASTROLABE~%")))
  (terpri pane)

  ;; Active tasks
  (with-drawing-options (pane :ink +yellow+)
    (with-text-face (pane :bold)
      (format pane "  Tasks~%")))
  (let ((tasks (load-open-tasks 15)))
    (if tasks
        (dolist (task tasks)
          (present-task pane task))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no open tasks)~%"))))
  (terpri pane)

  ;; Active projects
  (with-drawing-options (pane :ink +green+)
    (with-text-face (pane :bold)
      (format pane "  Projects~%")))
  (let ((projects (load-active-projects 10)))
    (if projects
        (dolist (project projects)
          (present-project pane project))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no active projects)~%"))))
  (terpri pane)

  ;; Recent notes
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  Recent Notes~%")))
  (let ((notes (load-recent-notes 10)))
    (if notes
        (dolist (note notes)
          (present-note pane note))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no notes yet)~%"))))
  (terpri pane)

  ;; Persons
  (with-drawing-options (pane :ink +magenta+)
    (with-text-face (pane :bold)
      (format pane "  Contacts~%")))
  (let ((persons (load-persons 10)))
    (if persons
        (dolist (person persons)
          (present-person pane person))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no contacts yet)~%"))))
  (terpri pane)

  ;; Recent snippets
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  Snippets~%")))
  (let ((snippets (load-recent-snippets 10)))
    (if snippets
        (dolist (snippet snippets)
          (present-snippet pane snippet))
        (with-drawing-options (pane :ink +white+)
          (format pane "    (no snippets yet)~%")))))

(defun display-project-nav (pane)
  "Display a project's contents in the navigation pane."
  (if (null *current-project*)
      (display-home-nav pane)
      (let ((project *current-project*))
        (with-drawing-options (pane :ink +green+)
          (with-text-face (pane :bold)
            (format pane "  ~A~%" (project-name project))))
        (with-drawing-options (pane :ink +white+)
          (format pane "  ~A~%" (project-description project)))
        (terpri pane)

        ;; Project tasks
        (with-drawing-options (pane :ink +yellow+)
          (with-text-face (pane :bold)
            (format pane "  Tasks~%")))
        (let ((tasks (load-project-tasks (obj-id project))))
          (if tasks
              (dolist (task tasks)
                (present-task pane task))
              (with-drawing-options (pane :ink +white+)
                (format pane "    (no tasks)~%"))))
        (terpri pane)

        ;; Project notes (via links)
        (with-drawing-options (pane :ink +cyan+)
          (with-text-face (pane :bold)
            (format pane "  Notes~%")))
        (let ((linked (load-linked-objects project))
              (notes nil))
          (dolist (link linked)
            (when (string-equal (first link) "note")
              (let ((note (load-note (second link))))
                (when note (push note notes)))))
          (if notes
              (dolist (note (nreverse notes))
                (present-note pane note))
              (with-drawing-options (pane :ink +white+)
                (format pane "    (no notes)~%")))))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Helper — present any object by type
;;; ─────────────────────────────────────────────────────────────────────

(defun present-object (pane obj)
  "Present any astrolabe object as a clickable presentation."
  (cond
    ((typep obj 'note)    (present-note pane obj))
    ((typep obj 'task)    (present-task pane obj))
    ((typep obj 'project) (present-project pane obj))
    ((typep obj 'person)  (present-person pane obj))
    ((typep obj 'snippet) (present-snippet pane obj))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Search results view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-search-nav (pane)
  "Display search results in the navigation pane."
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  Search: ~A~%" (or *search-query* ""))))
  (terpri pane)
  (if *search-results*
      (dolist (obj *search-results*)
        (present-object pane obj))
      (with-drawing-options (pane :ink +white+)
        (format pane "    (no results)~%"))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Tag filter view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-tag-filter-nav (pane)
  "Display objects matching a tag filter."
  (with-drawing-options (pane :ink +yellow+)
    (with-text-face (pane :bold)
      (format pane "  Tag: ~A~%" (or *filter-tag* ""))))
  (terpri pane)
  (if *filter-results*
      (dolist (obj *filter-results*)
        (present-object pane obj))
      (with-drawing-options (pane :ink +white+)
        (format pane "    (no tagged objects)~%"))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Task list view
;;; ─────────────────────────────────────────────────────────────────────

(defun display-tasks-nav (pane)
  "Display filtered task list."
  (with-drawing-options (pane :ink +yellow+)
    (with-text-face (pane :bold)
      (format pane "  Tasks~A~%"
              (case *task-filter*
                (:all   " (all open)")
                (:today " (today)")
                (t      "")))))
  (terpri pane)
  (if *task-filter-results*
      (dolist (task *task-filter-results*)
        (present-task pane task))
      (with-drawing-options (pane :ink +white+)
        (format pane "    (no tasks)~%"))))

;;; ─────────────────────────────────────────────────────────────────────
;;; Detail pane — right side, shows selected object
;;; ─────────────────────────────────────────────────────────────────────

(defun display-detail (frame pane)
  "Display function for the detail pane."
  (declare (ignore frame))
  (if *current-object*
      (display-object-detail pane *current-object*)
      (display-welcome pane)))

(defun display-welcome (pane)
  "Display a welcome message when nothing is selected."
  (terpri pane)
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  Welcome to Astrolabe~%")))
  (terpri pane)
  (with-drawing-options (pane :ink +white+)
    (format pane "  Navigate notes, tasks, systems, and signals.~%")
    (terpri pane)
    (format pane "  Create:~%")
    (format pane "    Capture Note [title]     — create a note~%")
    (format pane "    Add Task [title]         — create a task~%")
    (format pane "    New Project [name]       — create a project~%")
    (format pane "    Add Person [name]        — add a contact~%")
    (format pane "    Capture Snippet [text]   — save a snippet~%")
    (terpri pane)
    (format pane "  Actions:~%")
    (format pane "    Complete Task [task]     — mark task done~%")
    (format pane "    Link [source] [target]  — link two objects~%")
    (terpri pane)
    (format pane "  Delete:~%")
    (format pane "    Delete Note [note]       — soft-delete a note~%")
    (format pane "    Delete Task [task]       — soft-delete a task~%")
    (format pane "    Delete Project [project] — soft-delete a project~%")
    (format pane "    Delete Person [person]   — soft-delete a contact~%")
    (format pane "    Delete Snippet [snippet] — soft-delete a snippet~%")
    (terpri pane)
    (format pane "  Navigate:~%")
    (format pane "    Home                     — return to home~%")
    (format pane "    Quit                     — exit Astrolabe~%")
    (terpri pane)
    (format pane "  Quick keys:~%")
    (format pane "    C-n  Capture Note~%")
    (format pane "    C-t  Add Task~%")
    (format pane "    C-s  Search~%")
    (format pane "    C-h  Home~%")
    (terpri pane)
    (format pane "  Click any item to see its details.~%")
    (format pane "  Tab cycles focus between panes.~%")))

(defgeneric display-object-detail (pane object)
  (:documentation "Display the detail view for an object."))

(defun display-tags (pane object)
  "Display tags for an object, if any."
  (let ((tags (load-tags-for-object object)))
    (when tags
      (with-drawing-options (pane :ink +yellow+)
        (format pane "  Tags: ~{~A~^, ~}~%" (mapcar #'second tags))))))

(defmethod display-object-detail (pane (note note))
  (terpri pane)
  (with-drawing-options (pane :ink +cyan+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (note-title note))))
  (when (obj-created-at note)
    (with-drawing-options (pane :ink +white+)
      (format pane "  Created: ~A~%" (obj-created-at note))))
  (when (obj-updated-at note)
    (with-drawing-options (pane :ink +white+)
      (format pane "  Updated: ~A~%" (obj-updated-at note))))
  (terpri pane)
  (display-tags pane note)
  (terpri pane)
  (let ((body (note-body note)))
    (when (and body (> (length body) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" body))))
  (display-links pane note))

(defmethod display-object-detail (pane (person person))
  (terpri pane)
  (with-drawing-options (pane :ink +magenta+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (person-name person))))
  (with-drawing-options (pane :ink +white+)
    (when (person-first-name person)
      (format pane "  Name:     ~A~A~%"
              (person-first-name person)
              (if (person-last-name person)
                  (format nil " ~A" (person-last-name person)) "")))
    (when (person-nickname person)
      (format pane "  Nickname: ~A~%" (person-nickname person)))
    (when (person-email person)
      (format pane "  Email:    ~A~%" (person-email person)))
    (when (person-email2 person)
      (format pane "  Email 2:  ~A~%" (person-email2 person)))
    (when (person-phone person)
      (format pane "  Phone:    ~A~%" (person-phone person)))
    (when (person-phone2 person)
      (format pane "  Phone 2:  ~A~%" (person-phone2 person)))
    (when (person-organization person)
      (format pane "  Org:      ~A~%" (person-organization person)))
    (when (person-job-title person)
      (format pane "  Title:    ~A~%" (person-job-title person)))
    (when (person-role person)
      (format pane "  Role:     ~A~%" (person-role person)))
    (when (person-website person)
      (format pane "  Website:  ~A~%" (person-website person)))
    (when (person-address person)
      (format pane "  Address:  ~A~%" (person-address person))
      (when (person-city person)
        (format pane "            ~A~A ~A~%"
                (person-city person)
                (if (person-state person)
                    (format nil ", ~A" (person-state person)) "")
                (or (person-postal-code person) "")))
      (when (person-country person)
        (format pane "            ~A~%" (person-country person))))
    (when (person-birthday person)
      (format pane "  Birthday: ~A~%" (person-birthday person)))
    (when (person-xmpp-jid person)
      (format pane "  XMPP:     ~A~%" (person-xmpp-jid person)))
    (when (person-matrix-id person)
      (format pane "  Matrix:   ~A~%" (person-matrix-id person)))
    (when (person-irc-nick person)
      (format pane "  IRC:      ~A~%" (person-irc-nick person)))
    (when (person-last-contacted person)
      (format pane "  Last contact: ~A~%" (person-last-contacted person)))
    (when (person-contact-frequency person)
      (format pane "  Frequency:    ~A~%" (person-contact-frequency person)))
    (when (obj-created-at person)
      (format pane "  Created:  ~A~%" (obj-created-at person))))
  (terpri pane)
  (let ((notes (person-notes person)))
    (when (and notes (> (length notes) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" notes))
      (terpri pane)))
  (display-tags pane person)
  (display-links pane person))

(defmethod display-object-detail (pane (snippet snippet))
  (terpri pane)
  (with-drawing-options (pane :ink +white+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (obj-display-title snippet))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Type: ~A~%" (snippet-content-type snippet))
    (when (snippet-language snippet)
      (format pane "  Language: ~A~%" (snippet-language snippet)))
    (when (snippet-source snippet)
      (format pane "  Source: ~A~%" (snippet-source snippet)))
    (when (obj-created-at snippet)
      (format pane "  Created: ~A~%" (obj-created-at snippet))))
  (terpri pane)
  (with-drawing-options (pane :ink +white+)
    (format pane "  ~A~%" (snippet-content snippet)))
  (terpri pane)
  (display-tags pane snippet)
  (display-links pane snippet))

(defmethod display-object-detail (pane (task task))
  (terpri pane)
  (with-drawing-options (pane :ink (task-priority-ink (task-priority task)))
    (with-text-face (pane :bold)
      (format pane "  ~A ~A~%" (task-status-marker (task-status task)) (task-title task))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Status:   ~A~%" (task-status task))
    (format pane "  Priority: ~A~%" (task-priority task))
    (when (task-due-date task)
      (format pane "  Due:      ~A~%" (task-due-date task)))
    (when (task-scheduled-date task)
      (format pane "  Scheduled: ~A~%" (task-scheduled-date task)))
    (when (task-completed-at task)
      (format pane "  Completed: ~A~%" (task-completed-at task)))
    (when (task-context task)
      (format pane "  Context:  ~A~%" (task-context task)))
    (when (task-effort-minutes task)
      (format pane "  Effort:   ~Dmin~A~%" (task-effort-minutes task)
              (if (task-actual-minutes task)
                  (format nil " (actual: ~Dmin)" (task-actual-minutes task))
                  "")))
    (when (task-recurrence task)
      (format pane "  Recurs:   ~A~%" (task-recurrence task)))
    (when (obj-created-at task)
      (format pane "  Created:  ~A~%" (obj-created-at task))))
  (display-tags pane task)
  (terpri pane)
  (let ((desc (task-description task)))
    (when (and desc (> (length desc) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" desc))
      (terpri pane)))
  (let ((notes (task-notes task)))
    (when (and notes (> (length notes) 0))
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Notes:~%"))
        (format pane "  ~A~%" notes))
      (terpri pane)))
  ;; Subtasks
  (when (obj-id task)
    (let ((subtasks (load-subtasks (obj-id task))))
      (when subtasks
        (with-drawing-options (pane :ink +yellow+)
          (with-text-face (pane :bold)
            (format pane "  Subtasks:~%")))
        (dolist (st subtasks)
          (present-task pane st))
        (terpri pane))))
  (display-links pane task))

(defmethod display-object-detail (pane (project project))
  (terpri pane)
  (with-drawing-options (pane :ink +green+)
    (with-text-face (pane :bold)
      (format pane "  ~A~%" (project-name project))))
  (with-drawing-options (pane :ink +white+)
    (format pane "  Status:   ~A~%" (project-status project))
    (format pane "  Priority: ~A~%" (project-priority project))
    (when (project-area project)
      (format pane "  Area:     ~A~%" (project-area project)))
    (when (project-start-date project)
      (format pane "  Started:  ~A~%" (project-start-date project)))
    (when (project-target-date project)
      (format pane "  Target:   ~A~%" (project-target-date project)))
    (when (project-completed-at project)
      (format pane "  Completed: ~A~%" (project-completed-at project)))
    (when (obj-created-at project)
      (format pane "  Created:  ~A~%" (obj-created-at project))))
  (display-tags pane project)
  (terpri pane)
  (let ((desc (project-description project)))
    (when (and desc (> (length desc) 0))
      (with-drawing-options (pane :ink +white+)
        (format pane "  ~A~%" desc))
      (terpri pane)))
  (let ((pnotes (project-notes project)))
    (when (and pnotes (> (length pnotes) 0))
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Notes:~%"))
        (format pane "  ~A~%" pnotes))
      (terpri pane)))
  ;; Task progress
  (let ((tasks (load-project-tasks (obj-id project))))
    (let ((total (length tasks))
          (done (count-if (lambda (tk) (string-equal (task-status tk) "done")) tasks)))
      (with-drawing-options (pane :ink +yellow+)
        (with-text-face (pane :bold)
          (format pane "  Tasks: ~D/~D complete~%" done total))))
    ;; Show open tasks inline
    (let ((open (remove-if (lambda (tk) (string-equal (task-status tk) "done")) tasks)))
      (dolist (task open)
        (present-task pane task))))
  (terpri pane)
  ;; Linked persons
  (let* ((linked (load-linked-objects project))
         (persons nil))
    (dolist (link linked)
      (when (string-equal (first link) "person")
        (let ((p (load-person (second link))))
          (when p (push p persons)))))
    (when persons
      (with-drawing-options (pane :ink +magenta+)
        (with-text-face (pane :bold)
          (format pane "  People:~%")))
      (dolist (p (nreverse persons))
        (present-person pane p))
      (terpri pane)))
  (display-links pane project))

(defun display-links (pane object)
  "Display linked objects for OBJECT."
  (let ((linked (load-linked-objects object)))
    (when linked
      (with-drawing-options (pane :ink +white+)
        (with-text-face (pane :bold)
          (format pane "  Linked:~%")))
      (dolist (link linked)
        (let* ((type-name (first link))
               (id (second link))
               (relation (third link))
               (obj (load-object-by-type-and-id type-name id)))
          (when obj
            (with-drawing-options (pane :ink +white+)
              (format pane "    ~A " (or relation "—")))
            (present-object pane obj)))))))
